version: '3.5'

x-daemon: &app-or-daemon
  build:
    context: .
  volumes:
    - ./Gemfile:/home/app/Gemfile
    - ./Gemfile.lock:/home/app/Gemfile.lock
    - ./app:/home/app/app
    - ./bin:/home/app/bin
    - ./.bundle:/home/app/.bundle
    - ./.cache:/home/app/.cache
    - ./config:/home/app/config
    - ./db:/home/app/db
    - ./lib:/home/app/lib
    - ./.local:/home/app/.local
    - ./log:/home/app/log
    - ./node_modules:/home/app/node_modules
    - ./public:/home/app/public
    - ./storage:/home/app/storage
    - ./test:/home/app/test
    - ./tmp:/home/app/tmp
    - ./vendor:/home/app/vendor
  env_file:
    - ./app.env

services:
  app:
    << : *app-or-daemon
    tty: true
    stdin_open: true
    environment:
    # jwilder nginx-proxy specific environment variables
      - VIRTUAL_HOST=tracking-app.papievis.com
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=http
      - SSL_POLICY=Mozilla-Modern
      - LETSENCRYPT_HOST=tracking-app.papievis.com
      - LETSENCRYPT_EMAIL=postmaster@papievis.com

  record:
    << : *app-or-daemon
    tty: true
    stdin_open: true
    command: bundle exec ruby lib/daemons/amqp_daemon.rb record

  redis:
    image: redis:4.0.10
    restart: always
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.7.6-management
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
    # jwilder nginx-proxy specific environment variables
      - VIRTUAL_HOST=tracking-app-mq.papievis.com
      - VIRTUAL_PORT=15672
      - VIRTUAL_PROTO=http
      - SSL_POLICY=Mozilla-Modern
      - LETSENCRYPT_HOST=tracking-app-mq.papievis.com
      - LETSENCRYPT_EMAIL=postmaster@papievis.com

volumes:
  rabbitmq_data:
  redis_data:

# jwilder nginx-proxy specific network
networks:
  default:
    external:
      name: nginx-proxy
