connect:
  host: <%= ENV.fetch('RABBITMQ_HOST', 'localhost') %>
  port: <%= ENV.fetch('RABBITMQ_PORT', '5672') %>
  username: <%= ENV.fetch('RABBITMQ_USER', 'guest') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD', 'guest') %>

exchange:
  # record:
  #   name: app.record
  #   type: fanout

queue:
  record:
    name: app.record
    durable: true
    # You can set queue maximum length (see https://www.rabbitmq.com/maxlength.html).
    # For order matching queue it is recommended to set limit about to 10000 per market.
    # So in case you have 10 markets you would set 1000000. But this value is relative and depends on your business (market load).
    #
    # max_length: 10000
    #
    # Alternatively you can pass custom arguments here (for example in case your use RabbitMQ plugins):
    #
    # arguments:
    #   x-max-length: 10000
    #
    # When you change any parameter of queue definition it is required to drop it in RabbitMQ admin panel.
    # In case you want this to be done transparently and automatically I recommend to set auto_delete to true.
    #
    # auto_delete: true
    #
    # In such case queue will be deleted automatically once all workers are disconnected. This should ensure queue
    # is created from scratch with new configuration at next redeployment.


binding:
  record:
    queue: record
    # exchange: record

channel:
  trade_executor:
    prefetch: 5
  order_processor:
    prefetch: 5
